before_script:
  - nvm use 20.15.0
  - node -v

stages:
  - clean
  - build_admin
  - build_server
  - build_main

clean1:
  stage: clean
  only:
    - prod
  script:
    - cd /home/wwwroot/nav.geekape.net/
    - rm -rf web server admin
    - pm2 stop all
    - pm2 delete all
    - echo "清空nav.geekape.net目录成功"
  allow_failure: true

# 打包 admin
build_admin:
  stage: build_admin
  only:
    - prod
  script:
    # 将镜像源设置成淘宝镜像
    - npm set registry 'https://registry.npmmirror.com'
    - cd apps
    - cd nav-admin
    - npm install
    - echo "admin 安装完成"
    - npm run build
    - echo "admin 打包完成"
    - mv dist/ /home/wwwroot/nav.geekape.net/
    - echo "admin 移动目录完成"
  allow_failure: true

# 打包 server
build_server:
  stage: build_server
  only:
    - prod
  script:
    - mv geekape-nav-server/ /home/wwwroot/nav.geekape.net/
    - echo "server 移动目录完成"
    - cd /home/wwwroot/nav.geekape.net/
    - mv geekape-nav-server server
    - cd server/
    - yarn install
    - echo "server 包安装完成"
    - rm -rf /home/wwwroot/nav.geekape.net/server/config/mongodb.ts
    - cp /home/wwwroot/nav.geekape.net/mongodb.ts /home/wwwroot/nav.geekape.net/server/config/
    - pm2 start npm --name "geekape-nav-server" -- run server
    - echo "pm2 server启动成功"
  allow_failure: true
  
# 打包 page
build_page:
  stage: build_page
  only:
    - prod
  script:
    - mv geekape-nav-main/ /home/wwwroot/nav.geekape.net/
    - cd /home/wwwroot/nav.geekape.net/
    - mv geekape-nav-main web
    - cd web/
    - yarn install
    - echo "page 包安装完成"
    - yarn build
    - echo "page 打包完成，可以运行"
    - pm2 start npm --name "geekape-nav-main" -- run server
    - echo "pm2 main 启动成功"
  allow_failure: true

    